account/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from account.views import Registration, UserDetail

urlpatterns = patterns('',
    url(r'^registration/', Registration.as_view(), name='registration'),
    url(r'^login/', 'django.contrib.auth.views.login', kwargs={'template_name': 'account/login.html'}, name='login'),
    url(r'^logout/', 'django.contrib.auth.views.logout', kwargs={'next_page': '/'}, name='logout'),
    url(r'^profile/', login_required(UserDetail.as_view()), name='detail'),
)

application/urls.py
from django.conf.urls import patterns, include, url
from product.views import ProductList

urlpatterns = patterns('',
    url(r'^$', ProductList.as_view(), name='frontpage'),

    url(r'^account/', include('account.urls', namespace='account')),

    url(r'^product/', include('product.urls', namespace='product')),

    url(r'^order/', include('order.urls', namespace='order')),
)

order/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from application import settings
from order.views import OrderList, OrderCreate, OrderDetail, OrderUpdate


urlpatterns = patterns('',
    url(r'^$', login_required(OrderList.as_view(), login_url=settings.LOGIN_URL), name='list'),
    url(r'^create/$', login_required(OrderCreate.as_view(), login_url=settings.LOGIN_URL), name='create'),
    url(r'^(?P<pk>\d+)/$', login_required(OrderDetail.as_view(), login_url=settings.LOGIN_URL), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', login_required(OrderUpdate.as_view(), login_url=settings.LOGIN_URL), name='update'),
)

product/urls.py
from django.conf.urls import patterns, url
from product.views import ProductList, ProductDetail

urlpatterns = patterns('',
    url(r'^$', ProductList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', ProductDetail.as_view(), name='detail'),
)

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass

order/models.py
from django.core.urlresolvers import reverse
from django.db import models
from account.models import User
from product.models import Offer

class Address(models.Model):
    address = models.CharField(max_length=256)
    comment = models.TextField()


class Order(models.Model):
    STATUS_CHOICES = (
        (1, 'Created'),
        (2, 'Confirmed'),
        (3, 'Closed'),
    )
    offer = models.ForeignKey(Offer, related_name='orders')
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=1)
    user = models.ForeignKey(User, related_name='orders')
    # address = models.ForeignKey(Address, related_name='orders', blank=True, null=True)

    def __unicode__(self):
        return u'{0}: {1}'.format(self.pk, self.offer.product)

    def get_absolute_url(self):
        return reverse('order:detail', kwargs={'pk': self.pk})

product/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=128)
    # image = models.ImageField()
    # likes = models.PositiveIntegerField()

    def __unicode__(self):
        return u'{0}'.format(self.name)


class Offer(models.Model):
    VOLUME_CHOICES = (
        (0, '1 gr'),
        (1, '1 kg'),
    )
    product = models.ForeignKey(Product, related_name='offers')
    volume = models.SmallIntegerField(choices=VOLUME_CHOICES, default=1)
    price = models.DecimalField(max_digits=10, decimal_places=4)

    def __unicode__(self):
        return u'{0} - {1}'.format(self.product.name, self.price)

account/forms.py
from django import forms
from account.models import User


class RegistrationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['confirm_password'] = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'password')

product/forms.py
from django import forms
from account.models import User


class RegistrationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['confirm_password'] = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'password')

account/views.py
from django import forms
from django.forms.utils import ErrorList
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, FormView
from account.forms import RegistrationForm
from account.models import User


class Registration(FormView):
    form_class = RegistrationForm
    template_name = 'account/registration.html'

    def form_valid(self, form):
        data = form.cleaned_data
        password_confimed = data['password'] == data['confirm_password']
        if password_confimed:

            User.objects.create_user(username=data['username'], password=data['password'], email='not@e.mail')
            return HttpResponseRedirect(reverse('account:login'))

        # add form error
        errors = form._errors.setdefault(forms.forms.NON_FIELD_ERRORS, ErrorList())
        errors.append('Passwords not same')
        return self.render_to_response(self.get_context_data(form=form))

class UserDetail(DetailView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user

order/views.py
# coding=utf-8
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, View, UpdateView
from order.models import Order
from product.models import Offer


class OrderView(View):
    model = Order

    def get_queryset(self):
        queryset = super(OrderView, self).get_queryset()
        user = self.request.user
        if user.is_superuser:
            return queryset

        return queryset.filter(user=self.request.user)


class OrderCreate(OrderView, CreateView):

    def post(self, request, *args, **kwargs):
        # FIXME: что то мне подсказывает, что это мощный костыль
        if 'pk' in request.POST:
            try:
                offer = Offer.objects.get(pk=request.POST['pk'])
            except Order.DoesNotExist:
                raise Http404

            order = Order.objects.create(offer=offer, user=request.user)
            return HttpResponseRedirect(reverse('order:detail', kwargs={'pk': order.pk}))

        return super(OrderCreate, self).post(request, *args, **kwargs)


class OrderDetail(OrderView, DetailView):
    pass


class OrderUpdate(OrderView, UpdateView):
    pass


class OrderList(OrderView, ListView):
    pass

product/views.py
from django.views.generic import ListView, DetailView
from product.models import Product


class ProductList(ListView):
    model = Product


class ProductDetail(DetailView):
    model = Product

order/templates/order/order_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Detail: {{ order }}</h1>
{% endblock %}

order/templates/order/order_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Order{% if order %}: {{ order }}{% endif %}</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if order %}
      <button type="submit">Create</button>
    {% else %}
      <button type="submit">Update</button>
    {% endif %}
  </form>
{% endblock %}

order/templates/order/order_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Orders list</h1>
<ul>
{% for order in order_list %}
  <li>
    <a href="{% url 'order:detail' order.pk %}">{{ order }}</a>
  </li>
{% empty %}
  <li>Empty</li>
{% endfor %}
</ul>
{% endblock %}

product/templates/product/product_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Detail: {{ product }}</h1>
<h2>Offers</h2>
<form action="{% url 'order:create' %}" method="post">
  <ul>
    {% csrf_token %}
    {% for offer in product.offers.all %}
      <li>
        <button type="submit" value="{{ offer.id }}" name="pk">
        {{ offer.volume }}: {{ offer.price }}
        </button>
      </li>
    {% endfor %}
  </ul>
</form>

{% endblock %}

product/templates/product/product_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Products list</h1>
  <form action="{% url 'order:create' %}" method="post">
    {% csrf_token %}
    <ul>
      {% for product in product_list %}
        <li>
          <a href="{% url 'product:detail' product.pk %}">{{ product }}</a>
          <ul>
          {% for offer in product.offers.all %}
            <li>
              <button type="submit" value="{{ offer.id }}" name="pk">
              {{ offer.volume }}: {{ offer.price }}
              </button>
            </li>
          {% endfor %}
          </ul>
        </li>
      {% empty %}
        <li>Empty</li>
      {% endfor %}
      </ul>
  </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
{% if user.is_authenticated %}
  <form action="{% url 'account:logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Logout</button>
  </form>
  <ul>
    <li><a href="{% url 'account:detail' %}">Profile</a></li>
    <li><a href="{% url 'product:list' %}">Products</a></li>
    <li><a href="{% url 'order:list' %}">Orders</a></li>
  </ul>
{% else %}
  <a href="{% url 'account:login' %}">Login</a>
  <a href="{% url 'account:registration' %}">Registration</a>
{% endif %}
{% block content %}{% endblock %}
</body>
</html>